name = "github"
main = "main.ts"
compatibility_date = "2025-07-28"
compatibility_flags = ["nodejs_compat"]
upload_source_maps = true

[[kv_namespaces]]
binding = "GITHUB_KV"
id = "fa47de77b5c94c938cc68c94c6a247a9"
preview_id = "e8f3338afa2645669d60e88f16876007"


[observability]
enabled = true

[triggers]
crons = ["0 * * * *"]
